# -*- coding: utf-8 -*-
"""loading_traindata and test data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jgHKfD1kokKeBLKYiI5dGeISoS7eMVue
"""

trainY

testY

print("Training model....")
model = RandomForestClassifier(n_estimators=100)
model.fit(trainX,trainY)