# -*- coding: utf-8 -*-
"""Label_encoding.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1flUxlwa5EqlE4K0PzgWyPgT9xATIswOj
"""

le = LabelEncoder()
trainY = le.fit_transform(trainY)
testY = le.transform(testY)
print(trainX.shape,trainY.shape)